# Generated by Django 5.2 on 2025-05-01 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('zoom_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='zoom_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_meetings', to='zoom_integration.zoommeeting'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classes.class'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classfeedback',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='classes.class'),
        ),
        migrations.AddField(
            model_name='classfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_feedbacks', to='classes.class'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='resources',
            field=models.ManyToManyField(related_name='classes', to='classes.resource'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['class_instance'], name='classes_cla_class_i_559392_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['student'], name='classes_cla_student_c8d8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['status'], name='classes_cla_status_6193aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classattendance',
            unique_together={('class_instance', 'student')},
        ),
        migrations.AddIndex(
            model_name='classfeedback',
            index=models.Index(fields=['class_instance'], name='classes_cla_class_i_fbde7e_idx'),
        ),
        migrations.AddIndex(
            model_name='classfeedback',
            index=models.Index(fields=['student'], name='classes_cla_student_bd6b75_idx'),
        ),
        migrations.AddIndex(
            model_name='classfeedback',
            index=models.Index(fields=['rating'], name='classes_cla_rating_4f8ef0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classfeedback',
            unique_together={('class_instance', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('class_instance', 'student')},
        ),
    ]
