# Generated by Django 5.2 on 2025-05-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='default_meeting_duration',
            field=models.IntegerField(default=60, help_text='Default meeting duration in minutes'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='max_participants',
            field=models.IntegerField(default=100, help_text='Maximum participants per meeting'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='meeting_templates',
            field=models.JSONField(default=list, help_text='Saved meeting templates'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='recording_settings',
            field=models.JSONField(default=dict, help_text='Recording preferences and settings'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='resource_categories',
            field=models.JSONField(default=list, help_text='Resource categories for the program'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='virtual_class_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='zoom_settings',
            field=models.JSONField(default=dict, help_text='Program-specific Zoom settings'),
        ),
    ]
