# Generated by Django 5.2 on 2025-05-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_term'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualClass',
        ),
    ]
